version: '3'

services:
  web:
    restart: always
    build: .
    command: bash -c "cd app && python3 manage.py collectstatic --no-input && python3 manage.py migrate && gunicorn --timeout=30 --workers=2 --bind :8000 core.wsgi:application"
    volumes:
      - .:/usr/src/code
      - static-volume:/usr/src/code/app/static
      - media-volume:/usr/src/code/app/media
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - web_network
      - db_network
  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      - '3307:3306'
    restart: always
    env_file:
      - .env.db
    networks:
      - db_network
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - static-volume:/usr/src/code/static
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  static-volume:
  media-volume: